### ISSUE TITLE
Collect problems that prevents a quick start

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-api#59]
Need to collect the problems that prevent a quick start and try to solve them.
This package is small and may be released soon.

I see at least one problem now, see #58.

**Comment by romkatsu** [comment]
1. I really want to use a [trait](https://github.com/yiisoft/yii-rest/blob/master/src/RestControllerTrait.php), but I need to make it return a custom exception. To register here and give the desired [code](https://github.com/romkatsu/yii-api-demo/blob/master/src/Middleware/ExceptionMiddleware.php).

2. I want to have a demo, similar to yii-demo.

3. I want to have application error handling out of the box(formatting)
https://github.com/romkatsu/yii-api-demo/blob/master/src/Middleware/ExceptionMiddleware.php
https://github.com/romkatsu/yii-api-demo/blob/master/src/NotFoundHandler.php

4. I would like to have a single point for formatting api responses out of the box(structure of the response).
https://github.com/romkatsu/yii-api-demo/blob/master/src/Formatter/ApiResponseFormatter.php

5. Many are faced with the problem of cors. They have to watch and choose from third-party solutions. I think it would be easier if there was middleware out of the box. 
https://github.com/yiisoft/yii-demo/issues/110

Perhaps all these problems are solved by the demo application.

**Comment by samdark** [comment]
1. Customizable request to entity mapping i.e. map request fields to Post form model.
2. Customizable entity to response fileds mapping i.e. map Post to array of fields to serialize to JSON then.
3. Paging / returning collection of entities.

**Comment by samdark** [comment]
- We need to implement a template: https://github.com/yiisoft/app-api
- We need a demo with API. Currently it is https://github.com/phpdigest/api
- Preliminary we don't want configurable CRUD. Instead we want Gii to be able to generate APIs. That may be reconsidered later.
