### ISSUE TITLE
Remove package?

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-api#77]
Looks like this package is no longer needed after https://github.com/yiisoft/yii-web/issues/275
@yiisoft/yii3 Anyone have arguments to leave this package?

**Comment by samdark** [comment]
1. Response factory is now part of data-response.
2. RestGroup and RestControllerTrait may be interesting.

@romkatsu what do you think?

**Comment by rustamwin** [comment]
> RestGroup and RestControllerTrait may be interesting.

We can move them to `app-api` template?

**Comment by romkatsu** [comment]
>     1. Response factory is now part of data-response.
> 
>     2. RestGroup and RestControllerTrait may be interesting.
> 
> 
> @romkatsu what do you think?

Let's move it to the template

**Comment by samdark** [comment]
@romkatsu would you please handle it?

**Comment by romkatsu** [comment]
> @romkatsu would you please handle it?

Ok.
